version: '3.6'
services:
  postgres:
    build: postgres-with-pgloader
    container_name: postgres-db
    ports:
      - '5431:5432'
    volumes:
      - pssql_data:/var/lib/postgresql/data
      - ./export:/tmp
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - '3307:3306'
    command:
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
      container_name: 'docker_phpmyadmin_mysql2pgsql'
      image: phpmyadmin/phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql
          - PMA_USER=root
          - PMA_PASSWORD=root_password
      ports:
          - '8080:80'
      volumes:
          - ./export:/sessions
      depends_on:
          - mysql
volumes:
  pssql_data:
  mysql_data:
